name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: php-actions/composer@v6
    - run: vendor/bin/phpunit --bootstrap vendor/autoload.php tests